# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zscgUCXJlJh6XVax5rytI46ZlHPU2ZXS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

"""Leitura do base de dados e normalização: Utilizou o Normalize age reescalando os dados por linhas e não por colunas """

data = pd.read_csv('winequality-red.csv')

normalized_geral = MinMaxScaler().fit_transform(data) #Normalizar toda base de dados

new_data = pd.DataFrame(normalized_geral, columns=['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol','quality']) #Adicionar rotulos 

array_x = np.array(new_data.drop('quality',1))
array_y = np.array(new_data['quality'])

"""Configuração geral do PCA para os cinco componentes"""

x = array_x
y = array_y
pca = PCA(n_components=5)
pca.fit(x)

print(pca.explained_variance_ratio_)
print(pca.singular_values_)

"""Tabela com os componentes do PCA"""

x_5 = pca.transform(x)
new_data = pd.DataFrame(x_5, columns=['pc1','pc2','pc3','pc4','pc5'])
new_data['target'] = y.flatten()

print(new_data)

"""Plot do gráfico com cinco componentes"""

sns.pairplot(
     new_data, vars = ['pc1','pc2', 'pc3', 'pc4', 'pc5'],
     hue='target', diag_kind="hist")
plt.show()

"""Configuração geral do PCA para os dez componentes"""

x = array_x
y = array_y

pca_10 = PCA(n_components=10)
pca_10.fit(x)

print(pca_10.explained_variance_ratio_)
print(pca_10.singular_values_)

"""Tabela dos dez principais componentes"""

x_10 = pca_10.transform(x)
new_data_10 = pd.DataFrame(x_10, columns=['pc1','pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10'])
new_data_10['target'] = y.flatten()

print(new_data_10)

"""Plot do gráfico com dez componentes"""

sns.pairplot(
     new_data_10, vars = ['pc1','pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10'],
     hue='target', diag_kind="hist")
plt.show()