# -*- coding: utf-8 -*-
"""Questão 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ba8DBdNQMnVPuyTSmE9IIoLsDzcesQ1d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn import preprocessing
from sklearn import utils
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

"""Pré-processamento dos dados"""

data = pd.read_csv('winequality-red.csv')

del_atributos = data.drop(['citric acid', 'density', 'pH', 'free sulfur dioxide'], axis=1) #Excluir os atributos 
normalized_geral = MinMaxScaler().fit_transform(del_atributos) #Normalizar toda base de dados
new_data = pd.DataFrame(normalized_geral, columns=['fixed acidity','volatile acidity','residual sugar','chlorides','total sulfur dioxide','sulphates','alcohol','quality']) #Adicionar rotulos 
X = np.array(new_data.drop('quality',1))
y = np.array(new_data['quality'])

"""Aplicando a PCA"""

pca = PCA(n_components=5)
pca.fit(X)

print(pca.explained_variance_ratio_)
#print(pca.singular_values_)

x_5 = pca.transform(X)
data_pca = pd.DataFrame(x_5, columns=['pc1','pc2','pc3','pc4','pc5'])
data_pca['target'] = y.flatten()

print(data_pca)

pca_x = np.array(data_pca.drop('target',1))
pca_y = np.array(data_pca['target'])

"""Divisão do conjunto de dados em tratamento e teste"""

X = pca_x
y = pca_y

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.30, random_state=0)

"""Aplicando o KNN com melhor valor de K"""

knn = KNeighborsRegressor(n_neighbors = 40, algorithm='ball_tree', metric='manhattan').fit(X_train, y_train)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

R2 = r2_score(y_test,y_pred) #Valor real e valor predito
print("R-Quadrado:", R2)

MSE = mean_squared_error(y_test,y_pred)
print("Erro Quadrático Médio:", MSE)

MAE = mean_absolute_error(y_test,y_pred)
print("Erro Absoluto Médio:", MAE)